// --------------------------------------------------------------------------
// Slice 004 / T027 — `POST /api/final-predictions` supersede behavior.
// --------------------------------------------------------------------------
// RED acceptance test for User Story 3 (P2) Acceptance Scenarios 1 + 2 —
// participant edits any one item; the prior value is preserved as a
// superseded version with timestamp; the new value becomes active; the
// supersede chain is reconstructible from the data layer (FR-010, spec §
// US3).
//
// Source of truth:
//   - specs/004-final-predictions/contracts/final-predictions.write.md
//     § Stored procedure semantics step 7 — SELECT existing active row
//     FOR UPDATE; INSERT new row; UPDATE old SET superseded_at = now(),
//     superseded_by = v_new_id.
//   - specs/004-final-predictions/contracts/final-predictions.read.md
//     § Server behavior step 3 — query filters `superseded_at IS NULL`.
//   - specs/004-final-predictions/spec.md § US3 Acceptance Scenarios 1, 2.
//
// Scenario covered:
//   Charlie POSTs champion=ARG (CREATE). Then POSTs champion=BRA (UPDATE /
//   supersede). Service-role verifies the supersede chain in the data
//   layer:
//     - 2 rows total for (charlie, champion).
//     - The first row (ARG): `superseded_at IS NOT NULL` AND
//       `superseded_by = <bra row id>`.
//     - The second row (BRA): `superseded_at IS NULL`.
//   Then GET /api/me/final-predictions confirms only the active BRA row
//   surfaces to the participant (FR-010 + read contract active-only
//   posture).
//
// Why charlie:
//   The slice-004 fixture seeds Charlie's `best_player` row (Pedri) but
//   does NOT seed any champion row for Charlie. The two POSTs in this
//   test therefore exercise CREATE-then-SUPERSEDE on a clean (charlie,
//   champion) pair, with no fixture row to confuse the chain assertion.
//
// Cleanup contract:
//   Service-role DELETE every `final_predictions` row for Charlie before
//   and after each test. Both DELETEs are safe — the fixture's only
//   Charlie row (best_player → Pedri) is regenerated by `supabase db
//   reset`; we do not need to preserve it across this test.
//
// RED until T029 ships the SP's supersede arm. Pre-T029, the SECOND POST
// returns 409 ALREADY_SUBMITTED and the test fails on that status
// assertion. Post-T029, the test flips to GREEN.
// --------------------------------------------------------------------------

import { test, expect } from "@playwright/test";

import {
  assertOidcStubReachable,
  resetStub,
  signInWithIdentity,
} from "./fixtures/oidc";
import { getServiceClient } from "./helpers/service-role";

const CHARLIE = {
  sub: "00000000-0000-0000-0000-00000000000c",
  participantId: "33333333-3333-3333-3333-333333333333",
  email: "charlie@nortal.com",
  email_verified: true,
  name: "Charlie Tester",
} as const;

const ARG_TEAM_ID = "aaaa0000-0000-0000-0000-000000000001";
const BRA_TEAM_ID = "aaaa0000-0000-0000-0000-000000000002";

interface FinalPredictionShape {
  id: string;
  item_kind: "champion" | "runner_up" | "top_scorer" | "best_player";
  target_team_id: string | null;
  target_player_id: string | null;
  submitted_at: string;
  source: "ui" | "api" | "admin_override";
  superseded_at: string | null;
}

interface SubmitResponse {
  final_prediction: FinalPredictionShape;
}

interface MeFinalPredictionsResponse {
  final_predictions: Array<{
    id: string;
    item_kind: string;
    target_team_id: string | null;
    target_player_id: string | null;
    submitted_at: string;
    source: string;
  }>;
  lock_state: "editable" | "locked";
  first_kickoff_utc: string | null;
}

async function deleteAllCharlieFinalPredictions(): Promise<void> {
  const client = getServiceClient();
  const { error } = await client
    .from("final_predictions")
    .delete()
    .eq("participant_id", CHARLIE.participantId);
  if (error) {
    throw new Error(
      `deleteAllCharlieFinalPredictions failed — ${error.message}`,
    );
  }
}

test.describe(
  "US3 — POST /api/final-predictions supersede preserves history; GET hides superseded row @slice-004 @us3",
  () => {
    test.beforeAll(async () => {
      await assertOidcStubReachable();
    });

    test.beforeEach(async () => {
      await resetStub();
      await deleteAllCharlieFinalPredictions();
    });

    test.afterEach(async () => {
      await resetStub();
      await deleteAllCharlieFinalPredictions();
    });

    test(
      "charlie POSTs champion=ARG then champion=BRA; data layer holds 2 rows in a supersede chain; GET returns only BRA @slice-004 @us3",
      async ({ page, request }) => {
        await signInWithIdentity(page, {
          claims: {
            sub: CHARLIE.sub,
            email: CHARLIE.email,
            email_verified: CHARLIE.email_verified,
            name: CHARLIE.name,
          },
        });

        const cookies = await page.context().cookies();
        const cookieHeader = cookies
          .map((c) => `${c.name}=${c.value}`)
          .join("; ");

        // ---- 1. CREATE champion = ARG ---------------------------------
        const create = await request.post("/api/final-predictions", {
          headers: { Cookie: cookieHeader },
          data: { item_kind: "champion", target_team_id: ARG_TEAM_ID },
        });
        expect(
          create.status(),
          "first POST (CREATE champion=ARG) MUST be 200",
        ).toBe(200);
        const createBody = (await create.json()) as SubmitResponse;
        const argPredId = createBody.final_prediction.id;
        expect(createBody.final_prediction).toMatchObject({
          item_kind: "champion",
          target_team_id: ARG_TEAM_ID,
          target_player_id: null,
          superseded_at: null,
        });

        // ---- 2. UPDATE / supersede champion = BRA ---------------------
        const update = await request.post("/api/final-predictions", {
          headers: { Cookie: cookieHeader },
          data: { item_kind: "champion", target_team_id: BRA_TEAM_ID },
        });
        expect(
          update.status(),
          "second POST (UPDATE/supersede champion to BRA) MUST be 200 — supersede arm is the US3 contract (T029)",
        ).toBe(200);
        const updateBody = (await update.json()) as SubmitResponse;
        const braPredId = updateBody.final_prediction.id;
        expect(
          braPredId,
          "supersede branch MUST INSERT a NEW row with a distinct id from the original",
        ).not.toBe(argPredId);
        expect(updateBody.final_prediction).toMatchObject({
          item_kind: "champion",
          target_team_id: BRA_TEAM_ID,
          target_player_id: null,
          superseded_at: null,
        });

        // ---- 3. Data-layer verification via service-role -------------
        // SELECT every (charlie, champion) row ordered by created_at so
        // [0] = ARG (older / superseded), [1] = BRA (newer / active).
        const client = getServiceClient();
        const { data: rows, error: selErr } = await client
          .from("final_predictions")
          .select(
            "id, item_kind, target_team_id, target_player_id, superseded_at, superseded_by, created_at",
          )
          .eq("participant_id", CHARLIE.participantId)
          .eq("item_kind", "champion")
          .order("created_at", { ascending: true });

        if (selErr) {
          throw new Error(
            `service-role SELECT failed — ${selErr.message}`,
          );
        }

        expect(
          rows,
          "service-role SELECT MUST return a non-null array",
        ).not.toBeNull();
        expect(
          rows!.length,
          "exactly 2 rows MUST persist for (charlie, champion) — 1 superseded + 1 active",
        ).toBe(2);

        const first = rows![0]!;
        const second = rows![1]!;

        // First row (ARG, oldest): superseded by the BRA row.
        expect(first.id).toBe(argPredId);
        expect(first.target_team_id).toBe(ARG_TEAM_ID);
        expect(first.target_player_id).toBeNull();
        expect(
          first.superseded_at,
          "the ARG row's `superseded_at` MUST be set (supersede chain step 9)",
        ).not.toBeNull();
        expect(
          first.superseded_by,
          "the ARG row's `superseded_by` MUST point at the BRA row (chain head)",
        ).toBe(braPredId);

        // Second row (BRA, newest): active.
        expect(second.id).toBe(braPredId);
        expect(second.target_team_id).toBe(BRA_TEAM_ID);
        expect(second.target_player_id).toBeNull();
        expect(
          second.superseded_at,
          "the active BRA row's `superseded_at` MUST be NULL",
        ).toBeNull();

        // ---- 4. GET /api/me/final-predictions hides the superseded row
        const list = await request.get("/api/me/final-predictions", {
          headers: { Cookie: cookieHeader },
        });
        expect(
          list.status(),
          "GET /api/me/final-predictions MUST be 200",
        ).toBe(200);

        const listBody = (await list.json()) as MeFinalPredictionsResponse;
        const championEntries = listBody.final_predictions.filter(
          (p) => p.item_kind === "champion",
        );
        expect(
          championEntries.length,
          "champion entry MUST appear EXACTLY ONCE in the active-only read (no history dup)",
        ).toBe(1);

        const champion = championEntries[0]!;
        expect(
          champion.id,
          "GET's champion id MUST be the active BRA row id",
        ).toBe(braPredId);
        expect(
          champion.target_team_id,
          "GET's champion target_team_id MUST be BRA (not the superseded ARG value)",
        ).toBe(BRA_TEAM_ID);
        expect(champion.target_player_id).toBeNull();

        // The superseded ARG row id MUST NOT leak into the response.
        const allIds = listBody.final_predictions.map((p) => p.id);
        expect(
          allIds,
          "superseded ARG row id MUST NOT leak into /api/me/final-predictions (read contract active-only)",
        ).not.toContain(argPredId);
      },
    );
  },
);
